// Autogenerated from Pigeon (v9.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.lizhi.flutter_pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any> {
  return listOf<Any>(
    exception.javaClass.simpleName,
    exception.toString(),
    "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
  )
}

enum class ResponseCode(val raw: Int) {
  SUCCESS(0),
  FAIL(1);

  companion object {
    fun ofRaw(raw: Int): ResponseCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RequestParam (
  val key: String,
  val data: Map<String?, Any?>? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): RequestParam {
      val key = list[0] as String
      val data = list[1] as Map<String?, Any?>?
      return RequestParam(key, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      key,
      data,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ResponseParam (
  val code: ResponseCode,
  val message: String? = null,
  val data: Map<String?, Any?>? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ResponseParam {
      val code = ResponseCode.ofRaw(list[0] as Int)!!
      val message = list[1] as String?
      val data = list[2] as Map<String?, Any?>?
      return ResponseParam(code, message, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      code.raw,
      message,
      data,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InitRequestParam (
  val key: String,
  val data: PushConfig

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): InitRequestParam {
      val key = list[0] as String
      val data = PushConfig.fromList(list[1] as List<Any?>)
      return InitRequestParam(key, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      key,
      data.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ObserverData (
  val callbackKey: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ObserverData {
      val callbackKey = list[0] as String
      return ObserverData(callbackKey)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      callbackKey,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ObserverRequestParam (
  val key: String,
  val data: ObserverData

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ObserverRequestParam {
      val key = list[0] as String
      val data = ObserverData.fromList(list[1] as List<Any?>)
      return ObserverRequestParam(key, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      key,
      data.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SetAliasRequestParam (
  val key: String,
  val alias: List<String?>

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): SetAliasRequestParam {
      val key = list[0] as String
      val alias = list[1] as List<String?>
      return SetAliasRequestParam(key, alias)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      key,
      alias,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PushConfig (
  val hostApp: String,
  val appId: String,
  val deviceId: String,
  val defaultHosts: List<String?>? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PushConfig {
      val hostApp = list[0] as String
      val appId = list[1] as String
      val deviceId = list[2] as String
      val defaultHosts = list[3] as List<String?>?
      return PushConfig(hostApp, appId, deviceId, defaultHosts)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      hostApp,
      appId,
      deviceId,
      defaultHosts,
    )
  }
}

/**
 *
 * 连接信息
 * */
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ConnInfo (

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ConnInfo {
      return ConnInfo()
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConnStatusObserverCallParam (
  val key: String,
  val data: ConnInfo

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): ConnStatusObserverCallParam {
      val key = list[0] as String
      val data = ConnInfo.fromList(list[1] as List<Any?>)
      return ConnStatusObserverCallParam(key, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      key,
      data.toList(),
    )
  }
}

/**
 *
 * 推送消息
 * */
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PushData (

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PushData {
      return PushData()
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PushObserverCallParam (
  val key: String,
  val data: PushData

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PushObserverCallParam {
      val key = list[0] as String
      val data = PushData.fromList(list[1] as List<Any?>)
      return PushObserverCallParam(key, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      key,
      data.toList(),
    )
  }
}

/**
 *
 * 订阅结果
 * */
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SubscribeResult (

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): SubscribeResult {
      return SubscribeResult()
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TopicData (
  val topic: String,
  val result: SubscribeResult

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): TopicData {
      val topic = list[0] as String
      val result = SubscribeResult.fromList(list[1] as List<Any?>)
      return TopicData(topic, result)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      topic,
      result.toList(),
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TopicObserverCallParam (
  val key: String,
  val data: TopicData

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): TopicObserverCallParam {
      val key = list[0] as String
      val data = TopicData.fromList(list[1] as List<Any?>)
      return TopicObserverCallParam(key, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      key,
      data.toList(),
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object NativePushBridgeCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitRequestParam.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ObserverData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ObserverRequestParam.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PushConfig.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RequestParam.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ResponseParam.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SetAliasRequestParam.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InitRequestParam -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is ObserverData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ObserverRequestParam -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PushConfig -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is RequestParam -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ResponseParam -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is SetAliasRequestParam -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativePushBridge {
  /**
   *
   * 连接
   * */
   */
  fun connect(param: InitRequestParam, callback: (Result<ResponseParam>) -> Unit)
  /**
   *
   * 断开连接
   * */
   */
  fun disconnect(): ResponseParam
  /**
   *
   * 添加连接状态监听
   * */
   */
  fun addConnStatusObserver(param: ObserverRequestParam): ResponseParam
  /**
   *
   * 移除连接状态监听
   * */
   */
  fun removeConnStatusObserver(param: ObserverRequestParam): ResponseParam
  /**
   *
   * 添加推送消息监听
   * */
   */
  fun addPushObserver(param: ObserverRequestParam): ResponseParam
  /**
   *
   * 移除连接状态监听
   * */
   */
  fun removePushObserver(param: ObserverRequestParam): ResponseParam
  /**
   *
   * 设置别名
   * */
   */
  fun setAlias(param: SetAliasRequestParam, callback: (Result<ResponseParam>) -> Unit)
  /**
   *
   * 清除别名
   * */
   */
  fun clearAlias(callback: (Result<ResponseParam>) -> Unit)
  /**
   *
   * 订阅主题
   * */
   */
  fun subscribeTopic(param: RequestParam): ResponseParam
  /**
   *
   * 取消订阅主题
   * */
   */
  fun unsubscribeTopic(param: RequestParam): ResponseParam
  /**
   *
   * 添加主题订阅监听
   * */
   */
  fun addTopicsObserver(param: ObserverRequestParam): ResponseParam
  /**
   *
   * 移除主题订阅监听
   * */
   */
  fun removeTopicsObserver(param: ObserverRequestParam): ResponseParam

  companion object {
    /** The codec used by NativePushBridge. */
    val codec: MessageCodec<Any?> by lazy {
      NativePushBridgeCodec
    }
    /** Sets up an instance of `NativePushBridge` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: NativePushBridge?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.NativePushBridge.connect", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramArg = args[0] as InitRequestParam
            api.connect(paramArg) { result: Result<ResponseParam> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.NativePushBridge.disconnect", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.disconnect())
            } catch (exception: Error) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.NativePushBridge.addConnStatusObserver", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramArg = args[0] as ObserverRequestParam
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.addConnStatusObserver(paramArg))
            } catch (exception: Error) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.NativePushBridge.removeConnStatusObserver", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramArg = args[0] as ObserverRequestParam
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.removeConnStatusObserver(paramArg))
            } catch (exception: Error) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.NativePushBridge.addPushObserver", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramArg = args[0] as ObserverRequestParam
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.addPushObserver(paramArg))
            } catch (exception: Error) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.NativePushBridge.removePushObserver", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramArg = args[0] as ObserverRequestParam
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.removePushObserver(paramArg))
            } catch (exception: Error) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.NativePushBridge.setAlias", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramArg = args[0] as SetAliasRequestParam
            api.setAlias(paramArg) { result: Result<ResponseParam> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.NativePushBridge.clearAlias", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearAlias() { result: Result<ResponseParam> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.NativePushBridge.subscribeTopic", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramArg = args[0] as RequestParam
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.subscribeTopic(paramArg))
            } catch (exception: Error) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.NativePushBridge.unsubscribeTopic", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramArg = args[0] as RequestParam
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.unsubscribeTopic(paramArg))
            } catch (exception: Error) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.NativePushBridge.addTopicsObserver", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramArg = args[0] as ObserverRequestParam
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.addTopicsObserver(paramArg))
            } catch (exception: Error) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.NativePushBridge.removeTopicsObserver", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramArg = args[0] as ObserverRequestParam
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.removeTopicsObserver(paramArg))
            } catch (exception: Error) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object FlutterPushBridgeCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnInfo.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnStatusObserverCallParam.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PushData.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PushObserverCallParam.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ResponseParam.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SubscribeResult.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TopicData.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TopicObserverCallParam.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ConnInfo -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is ConnStatusObserverCallParam -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PushData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PushObserverCallParam -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ResponseParam -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is SubscribeResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is TopicData -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is TopicObserverCallParam -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class FlutterPushBridge(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by FlutterPushBridge. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterPushBridgeCodec
    }
  }
  fun onConnStatusObserverCall(paramArg: ConnStatusObserverCallParam, callback: (ResponseParam) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.FlutterPushBridge.onConnStatusObserverCall", codec)
    channel.send(listOf(paramArg)) {
      val result = it as ResponseParam
      callback(result)
    }
  }
  fun onPushObserverCall(paramArg: PushObserverCallParam, callback: (ResponseParam) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.FlutterPushBridge.onPushObserverCall", codec)
    channel.send(listOf(paramArg)) {
      val result = it as ResponseParam
      callback(result)
    }
  }
  fun onTopicObserverCall(paramArg: TopicObserverCallParam, callback: (ResponseParam) -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.FlutterPushBridge.onTopicObserverCall", codec)
    channel.send(listOf(paramArg)) {
      val result = it as ResponseParam
      callback(result)
    }
  }
}
