// Autogenerated from Pigeon (v9.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

enum ResponseCode {
  success,
  fail,
}

enum ConnectStatus {
  connecting,
  connected,
  disconnect,
}

enum TopicResultStatus {
  invalid,
  processing,
  available,
}

class RequestParam {
  RequestParam({
    required this.key,
    this.data,
  });

  String key;

  Map<String?, Object?>? data;

  Object encode() {
    return <Object?>[
      key,
      data,
    ];
  }

  static RequestParam decode(Object result) {
    result as List<Object?>;
    return RequestParam(
      key: result[0]! as String,
      data: (result[1] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
    );
  }
}

class ResponseParam {
  ResponseParam({
    required this.code,
    this.message,
    this.data,
  });

  ResponseCode code;

  String? message;

  Map<String?, Object?>? data;

  Object encode() {
    return <Object?>[
      code.index,
      message,
      data,
    ];
  }

  static ResponseParam decode(Object result) {
    result as List<Object?>;
    return ResponseParam(
      code: ResponseCode.values[result[0]! as int],
      message: result[1] as String?,
      data: (result[2] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
    );
  }
}

class InitRequestParam {
  InitRequestParam({
    required this.key,
    required this.data,
  });

  String key;

  PushConfig data;

  Object encode() {
    return <Object?>[
      key,
      data.encode(),
    ];
  }

  static InitRequestParam decode(Object result) {
    result as List<Object?>;
    return InitRequestParam(
      key: result[0]! as String,
      data: PushConfig.decode(result[1]! as List<Object?>),
    );
  }
}

class ObserverData {
  ObserverData({
    required this.callbackKey,
  });

  String callbackKey;

  Object encode() {
    return <Object?>[
      callbackKey,
    ];
  }

  static ObserverData decode(Object result) {
    result as List<Object?>;
    return ObserverData(
      callbackKey: result[0]! as String,
    );
  }
}

class ObserverRequestParam {
  ObserverRequestParam({
    required this.key,
    required this.data,
  });

  String key;

  ObserverData data;

  Object encode() {
    return <Object?>[
      key,
      data.encode(),
    ];
  }

  static ObserverRequestParam decode(Object result) {
    result as List<Object?>;
    return ObserverRequestParam(
      key: result[0]! as String,
      data: ObserverData.decode(result[1]! as List<Object?>),
    );
  }
}

class SetAliasRequestParam {
  SetAliasRequestParam({
    required this.key,
    required this.alias,
  });

  String key;

  List<String?> alias;

  Object encode() {
    return <Object?>[
      key,
      alias,
    ];
  }

  static SetAliasRequestParam decode(Object result) {
    result as List<Object?>;
    return SetAliasRequestParam(
      key: result[0]! as String,
      alias: (result[1] as List<Object?>?)!.cast<String?>(),
    );
  }
}

class PushConfig {
  PushConfig({
    required this.hostApp,
    required this.appId,
    required this.deviceId,
    this.defaultHosts,
  });

  String hostApp;

  String appId;

  String deviceId;

  List<String?>? defaultHosts;

  Object encode() {
    return <Object?>[
      hostApp,
      appId,
      deviceId,
      defaultHosts,
    ];
  }

  static PushConfig decode(Object result) {
    result as List<Object?>;
    return PushConfig(
      hostApp: result[0]! as String,
      appId: result[1]! as String,
      deviceId: result[2]! as String,
      defaultHosts: (result[3] as List<Object?>?)?.cast<String?>(),
    );
  }
}

///
/// 连接信息
/// 
class ConnectInfo {
  ConnectInfo({
    required this.errorCode,
    this.errorMessage,
    this.connStatus,
  });

  int errorCode;

  String? errorMessage;

  ConnectStatus? connStatus;

  Object encode() {
    return <Object?>[
      errorCode,
      errorMessage,
      connStatus?.index,
    ];
  }

  static ConnectInfo decode(Object result) {
    result as List<Object?>;
    return ConnectInfo(
      errorCode: result[0]! as int,
      errorMessage: result[1] as String?,
      connStatus: result[2] != null
          ? ConnectStatus.values[result[2]! as int]
          : null,
    );
  }
}

class ConnStatusObserverCallParam {
  ConnStatusObserverCallParam({
    required this.key,
    required this.data,
  });

  String key;

  ConnectInfo data;

  Object encode() {
    return <Object?>[
      key,
      data.encode(),
    ];
  }

  static ConnStatusObserverCallParam decode(Object result) {
    result as List<Object?>;
    return ConnStatusObserverCallParam(
      key: result[0]! as String,
      data: ConnectInfo.decode(result[1]! as List<Object?>),
    );
  }
}

class TransferData {
  TransferData({
    this.seq,
    this.payloadId,
    this.payload,
    required this.timestamp,
    this.deviceId,
    this.alias,
    this.topic,
  });

  String? seq;

  String? payloadId;

  String? payload;

  int timestamp;

  String? deviceId;

  String? alias;

  String? topic;

  Object encode() {
    return <Object?>[
      seq,
      payloadId,
      payload,
      timestamp,
      deviceId,
      alias,
      topic,
    ];
  }

  static TransferData decode(Object result) {
    result as List<Object?>;
    return TransferData(
      seq: result[0] as String?,
      payloadId: result[1] as String?,
      payload: result[2] as String?,
      timestamp: result[3]! as int,
      deviceId: result[4] as String?,
      alias: result[5] as String?,
      topic: result[6] as String?,
    );
  }
}

///
/// 推送消息
/// 
class PushMessageData {
  PushMessageData({
    this.type,
    this.data,
  });

  String? type;

  TransferData? data;

  Object encode() {
    return <Object?>[
      type,
      data?.encode(),
    ];
  }

  static PushMessageData decode(Object result) {
    result as List<Object?>;
    return PushMessageData(
      type: result[0] as String?,
      data: result[1] != null
          ? TransferData.decode(result[1]! as List<Object?>)
          : null,
    );
  }
}

class PushObserverCallParam {
  PushObserverCallParam({
    required this.key,
    required this.data,
  });

  String key;

  PushMessageData data;

  Object encode() {
    return <Object?>[
      key,
      data.encode(),
    ];
  }

  static PushObserverCallParam decode(Object result) {
    result as List<Object?>;
    return PushObserverCallParam(
      key: result[0]! as String,
      data: PushMessageData.decode(result[1]! as List<Object?>),
    );
  }
}

///
/// 订阅结果
/// 
class TopicSubscribeResult {
  TopicSubscribeResult({
    required this.status,
    required this.code,
    this.msg,
  });

  TopicResultStatus status;

  int code;

  String? msg;

  Object encode() {
    return <Object?>[
      status.index,
      code,
      msg,
    ];
  }

  static TopicSubscribeResult decode(Object result) {
    result as List<Object?>;
    return TopicSubscribeResult(
      status: TopicResultStatus.values[result[0]! as int],
      code: result[1]! as int,
      msg: result[2] as String?,
    );
  }
}

class TopicSubscribeData {
  TopicSubscribeData({
    required this.topic,
    required this.result,
  });

  String topic;

  TopicSubscribeResult result;

  Object encode() {
    return <Object?>[
      topic,
      result.encode(),
    ];
  }

  static TopicSubscribeData decode(Object result) {
    result as List<Object?>;
    return TopicSubscribeData(
      topic: result[0]! as String,
      result: TopicSubscribeResult.decode(result[1]! as List<Object?>),
    );
  }
}

class TopicObserverCallParam {
  TopicObserverCallParam({
    required this.key,
    required this.data,
  });

  String key;

  TopicSubscribeData data;

  Object encode() {
    return <Object?>[
      key,
      data.encode(),
    ];
  }

  static TopicObserverCallParam decode(Object result) {
    result as List<Object?>;
    return TopicObserverCallParam(
      key: result[0]! as String,
      data: TopicSubscribeData.decode(result[1]! as List<Object?>),
    );
  }
}

class _NativePushBridgeCodec extends StandardMessageCodec {
  const _NativePushBridgeCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is InitRequestParam) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is ObserverData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is ObserverRequestParam) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PushConfig) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is RequestParam) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is ResponseParam) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is SetAliasRequestParam) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return InitRequestParam.decode(readValue(buffer)!);
      case 129: 
        return ObserverData.decode(readValue(buffer)!);
      case 130: 
        return ObserverRequestParam.decode(readValue(buffer)!);
      case 131: 
        return PushConfig.decode(readValue(buffer)!);
      case 132: 
        return RequestParam.decode(readValue(buffer)!);
      case 133: 
        return ResponseParam.decode(readValue(buffer)!);
      case 134: 
        return SetAliasRequestParam.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NativePushBridge {
  /// Constructor for [NativePushBridge].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativePushBridge({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _NativePushBridgeCodec();

  ///
  /// 连接
  /// 
  Future<ResponseParam> connect(InitRequestParam arg_param) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NativePushBridge.connect', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_param]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ResponseParam?)!;
    }
  }

  ///
  /// 断开连接
  /// 
  Future<ResponseParam> disconnect() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NativePushBridge.disconnect', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ResponseParam?)!;
    }
  }

  ///
  /// 添加连接状态监听
  /// 
  Future<ResponseParam> addConnStatusObserver(ObserverRequestParam arg_param) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NativePushBridge.addConnStatusObserver', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_param]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ResponseParam?)!;
    }
  }

  ///
  /// 移除连接状态监听
  /// 
  Future<ResponseParam> removeConnStatusObserver(ObserverRequestParam arg_param) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NativePushBridge.removeConnStatusObserver', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_param]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ResponseParam?)!;
    }
  }

  ///
  /// 添加推送消息监听
  /// 
  Future<ResponseParam> addPushObserver(ObserverRequestParam arg_param) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NativePushBridge.addPushObserver', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_param]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ResponseParam?)!;
    }
  }

  ///
  /// 移除连接状态监听
  /// 
  Future<ResponseParam> removePushObserver(ObserverRequestParam arg_param) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NativePushBridge.removePushObserver', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_param]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ResponseParam?)!;
    }
  }

  ///
  /// 设置别名
  /// 
  Future<ResponseParam> setAlias(SetAliasRequestParam arg_param) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NativePushBridge.setAlias', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_param]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ResponseParam?)!;
    }
  }

  ///
  /// 清除别名
  /// 
  Future<ResponseParam> clearAlias() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NativePushBridge.clearAlias', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ResponseParam?)!;
    }
  }

  ///
  /// 订阅主题
  /// 
  Future<ResponseParam> subscribeTopic(RequestParam arg_param) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NativePushBridge.subscribeTopic', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_param]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ResponseParam?)!;
    }
  }

  ///
  /// 取消订阅主题
  /// 
  Future<ResponseParam> unsubscribeTopic(RequestParam arg_param) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NativePushBridge.unsubscribeTopic', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_param]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ResponseParam?)!;
    }
  }

  ///
  /// 添加主题订阅监听
  /// 
  Future<ResponseParam> addTopicsObserver(ObserverRequestParam arg_param) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NativePushBridge.addTopicsObserver', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_param]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ResponseParam?)!;
    }
  }

  ///
  /// 移除主题订阅监听
  /// 
  Future<ResponseParam> removeTopicsObserver(ObserverRequestParam arg_param) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.NativePushBridge.removeTopicsObserver', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_param]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ResponseParam?)!;
    }
  }
}

class _FlutterPushBridgeCodec extends StandardMessageCodec {
  const _FlutterPushBridgeCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is ConnStatusObserverCallParam) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is ConnectInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PushMessageData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PushObserverCallParam) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is ResponseParam) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is TopicObserverCallParam) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is TopicSubscribeData) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is TopicSubscribeResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is TransferData) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return ConnStatusObserverCallParam.decode(readValue(buffer)!);
      case 129: 
        return ConnectInfo.decode(readValue(buffer)!);
      case 130: 
        return PushMessageData.decode(readValue(buffer)!);
      case 131: 
        return PushObserverCallParam.decode(readValue(buffer)!);
      case 132: 
        return ResponseParam.decode(readValue(buffer)!);
      case 133: 
        return TopicObserverCallParam.decode(readValue(buffer)!);
      case 134: 
        return TopicSubscribeData.decode(readValue(buffer)!);
      case 135: 
        return TopicSubscribeResult.decode(readValue(buffer)!);
      case 136: 
        return TransferData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class FlutterPushBridge {
  static const MessageCodec<Object?> codec = _FlutterPushBridgeCodec();

  ResponseParam onConnStatusObserverCall(ConnStatusObserverCallParam param);

  ResponseParam onPushObserverCall(PushObserverCallParam param);

  ResponseParam onTopicObserverCall(TopicObserverCallParam param);

  static void setup(FlutterPushBridge? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.FlutterPushBridge.onConnStatusObserverCall', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.FlutterPushBridge.onConnStatusObserverCall was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ConnStatusObserverCallParam? arg_param = (args[0] as ConnStatusObserverCallParam?);
          assert(arg_param != null,
              'Argument for dev.flutter.pigeon.FlutterPushBridge.onConnStatusObserverCall was null, expected non-null ConnStatusObserverCallParam.');
          final ResponseParam output = api.onConnStatusObserverCall(arg_param!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.FlutterPushBridge.onPushObserverCall', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.FlutterPushBridge.onPushObserverCall was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PushObserverCallParam? arg_param = (args[0] as PushObserverCallParam?);
          assert(arg_param != null,
              'Argument for dev.flutter.pigeon.FlutterPushBridge.onPushObserverCall was null, expected non-null PushObserverCallParam.');
          final ResponseParam output = api.onPushObserverCall(arg_param!);
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.FlutterPushBridge.onTopicObserverCall', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.FlutterPushBridge.onTopicObserverCall was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TopicObserverCallParam? arg_param = (args[0] as TopicObserverCallParam?);
          assert(arg_param != null,
              'Argument for dev.flutter.pigeon.FlutterPushBridge.onTopicObserverCall was null, expected non-null TopicObserverCallParam.');
          final ResponseParam output = api.onTopicObserverCall(arg_param!);
          return output;
        });
      }
    }
  }
}
